#server:
#  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:27001/railway
    username: postgres
    password: MDLvbuXFANRhkfwnupyxFlkoTdOQUNWo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none